// Bender 和 Novecento Wide。下载后的 sfnt 转成 woff2，并写出 fonts.css。

import { mkdir, readFile, rename, stat, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { joinUrl, rawBases } from "#compiler/download/source.js"
import type { DownloadJob } from "#compiler/download/downloader.js"
import { decodeWoff2Tables, encodeWoff2, readSfnt } from "./woff2.js"

export interface FontSource {
  readonly family: string
  readonly weight: number
  readonly style: string
  readonly src: string
  readonly name: string
  readonly ext: "otf" | "ttf"
  readonly bytes: number
}

export const fonts: readonly FontSource[] = Object.freeze([
  { family: "Bender", weight: 400, style: "normal", src: "Bender/BENDER.OTF", name: "bender-regular", ext: "otf", bytes: 52536 },
  { family: "Bender", weight: 300, style: "normal", src: "Bender/BenderLight.woff.ttf", name: "bender-light", ext: "ttf", bytes: 68256 },
  { family: "Novecento Wide", weight: 400, style: "normal", src: "Novecento-Wide-Normal-2.otf", name: "novecento-wide-normal", ext: "otf", bytes: 45356 },
])

export function fontJobs(): DownloadJob[] {
  return fonts.map((font) => ({
    rel: `${font.name}.${font.ext}`,
    urls: [joinUrl(rawBases.fonts, font.src)],
    kind: "font" as const,
    bytes: font.bytes,
  }))
}

export interface FontFaceFile {
  readonly family: string
  readonly weight: number
  readonly original?: string
  readonly woff2?: string
}

export interface FontBuild {
  readonly files: Readonly<Record<string, FontFaceFile>>
  readonly css: string | null
  readonly errors: readonly string[]
}

async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch {
    return false
  }
}

function errorMessage(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause)
}

export async function buildFonts(fontsDir: string, log: (message: string) => void = console.log): Promise<FontBuild> {
  await mkdir(fontsDir, { recursive: true })
  const files: Record<string, FontFaceFile> = {}
  const errors: string[] = []
  const faces: string[] = []
  for (const font of fonts) {
    const originalPath = join(fontsDir, `${font.name}.${font.ext}`)
    const woff2Path = join(fontsDir, `${font.name}.woff2`)
    if (!(await fileExists(originalPath))) {
      errors.push(`missing font ${font.name}.${font.ext}`)
      continue
    }
    const entry: { family: string; weight: number; original?: string; woff2?: string } = {
      family: font.family,
      weight: font.weight,
      original: `/fonts/${font.name}.${font.ext}`,
    }
    try {
      const source = await readFile(originalPath)
      readSfnt(source)
      let current = false
      if (await fileExists(woff2Path)) {
        try {
          const decoded = decodeWoff2Tables(await readFile(woff2Path))
          const sfnt = readSfnt(source)
          current =
            decoded.tables.length === sfnt.tables.length &&
            sfnt.tables.every((table) => decoded.tables.find((item) => item.tag === table.tag)?.data.equals(table.data))
        } catch {
          current = false
        }
      }
      if (!current) {
        const encoded = encodeWoff2(source)
        const temporary = woff2Path + ".tmp"
        await writeFile(temporary, encoded)
        await rename(temporary, woff2Path)
        log(`[fonts] ${font.name}.woff2 ${source.length} → ${encoded.length} B`)
      }
      entry.woff2 = `/fonts/${font.name}.woff2`
    } catch (cause) {
      errors.push(`${font.name}: ${errorMessage(cause)}`)
    }
    files[font.name] = entry
    const sources: string[] = []
    if (entry.woff2) sources.push(`url('${entry.woff2}') format('woff2')`)
    sources.push(`url('${entry.original}') format('${font.ext === "ttf" ? "truetype" : "opentype"}')`)
    faces.push(
      `@font-face {\n  font-family: '${font.family}';\n  font-style: ${font.style};\n  font-weight: ${font.weight};\n` +
        `  font-display: swap;\n  src: ${sources.join(",\n       ")};\n}`,
    )
  }
  let css: string | null = null
  if (faces.length) {
    css =
      `/* Generated by assets-catalog/compiler/font/build.ts — do not edit.\n` +
      ` * Bender (c) Jovanny Lemonad / Oleg Zhuravlev, Gladkikh Ivan — free font.\n` +
      ` * Novecento Wide (c) Jan Tonellato / Synthview — free font.\n` +
      ` * Usage: font-family: Bender, Rajdhani, 'Noto Sans SC', sans-serif;\n` +
      ` *        font-family: 'Novecento Wide', 'Saira Condensed', 'Noto Sans SC', sans-serif; */\n\n` +
      faces.join("\n\n") +
      "\n"
    await writeFile(join(fontsDir, "fonts.css"), css)
  }
  return { files, css, errors }
}
